services:
  postgres:
    ports:
      - "127.0.0.1:${POSTGRES_PORT_EXT:-15432}:5432"
  kafka:
    ports:
      - "127.0.0.1:${KAFKA_PORT_EXT:-19092}:${KAFKA_PORT_EXT:-19092}"
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_PORT:-9092},CONTROLLER://:9093,EXTERNAL://:${KAFKA_PORT_EXT:-19092}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:${KAFKA_PORT:-9092},EXTERNAL://${KAFKA_EXTERNAL:-localhost}:${KAFKA_PORT_EXT:-19092}
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "127.0.0.1:${KAFKA_UI_PORT:-8080}:8080"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:${KAFKA_PORT:-9092}
      - DYNAMIC_CONFIG_ENABLED=true
  migrate:
    build:
      context: ./db         
      dockerfile: Dockerfile.migrator
    depends_on:
      postgres: { condition: service_healthy }
    volumes:
      - ./db/migrations:/migrations:ro,z
    environment:
      - DATABASE_URL=${DATABASE_URL}
    entrypoint: ["migrate", "-path=/migrations", "-database", "${DATABASE_URL}"]
    restart: "no"
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "127.0.0.1:${PGADMIN_PORT:-15050}:80"  
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin_data:/var/lib/pgadmin            
    depends_on:
      postgres:
        condition: service_healthy
volumes:
    pgadmin_data:

