 services:
  migrate:
    build:
      context: ./db         
      dockerfile: Dockerfile.migrator
    depends_on:
      postgres: { condition: service_healthy }
    volumes:
      - ./db/migrations:/migrations:ro,z
    environment:
      - DATABASE_URL=${DATABASE_URL}
    entrypoint: ["migrate", "-path=/migrations", "-database", "${DATABASE_URL}"]
    restart: "no"